-- ════════════════════════════════════════════════════════════════════════════
--  G — VÉRIFICATIONS, À COLLER APRÈS G-migrations-a-coller.sql
-- ════════════════════════════════════════════════════════════════════════════
-- Généré par docs/production/G-generer.sh. LECTURE SEULE.
-- Une ligne par contrôle : statut OK ou PAS OK, et dans « détail » ce qui manque
-- ou diffère. Les valeurs attendues viennent du rejeu local en postgres ; elles
-- ne sont pas écrites à la main.
-- Éprouvé : toutes les lignes OK sur une copie migrée, toutes PAS OK sur une
-- copie non migrée.
-- ════════════════════════════════════════════════════════════════════════════
with
mig(version, name) as (values
    ('20260823000000','reference_schema_from_live'),
    ('20260823150000','cleanup_inherited_anomalies'),
    ('20260825160000','lot4_billing'),
    ('20260827100000','catalog_reference_data'),
    ('20260827101000','brief_autosave_and_preview'),
    ('20260827102000','brand_kit_deliverable'),
    ('20260827103000','rendering_constraints'),
    ('20260827104000','launch_checklist_items'),
    ('20260827105000','monthly_content_calendar'),
    ('20260827106000','subscription_state'),
    ('20260827107000','english_only_schema'),
    ('20260830060048','site_spec'),
    ('20260830060159','site_spec_catalog'),
    ('20260830060321','site_spec_preview_and_contrast'),
    ('20260830060424','site_spec_endpoints'),
    ('20260830060516','site_output_prompt'),
    ('20260830060617','site_output_setup_sheet'),
    ('20260830060701','site_spec_actions'),
    ('20260830060712','site_spec_hot_path'),
    ('20260830060759','site_spec_accent'),
    ('20260830060903','site_spec_limits_and_clamp'),
    ('20260830061029','site_output_templates'),
    ('20260830061046','site_spec_suggest_hex_bounds'),
    ('20260830061119','null_safe_jsonb_validators'),
    ('20260830061318','site_spec_paper'),
    ('20260830061402','palette_accent'),
    ('20260830061432','direction_limits'),
    ('20260830061454','etag_completeness'),
    ('20260830061516','step_title_counts'),
    ('20260830061639','text_safe_variants'),
    ('20260830061753','cta_ink_and_size_floor'),
    ('20260830062004','practitioner_name_and_voice_guide'),
    ('20260830062021','cta_size_floor_correction'),
    ('20260830062040','derive_variants_only_when_inputs_move'),
    ('20260830062227','entitlement_and_generation_credits'),
    ('20260830062241','entitlement_rpc_surface'),
    ('20260830062321','plans_and_granted_allowance'),
    ('20260901074421','direction_assets'),
    ('20260901074458','brand_kit_reveal'),
    ('20260901074515','reveal_specialties'),
    ('20260901074531','reveal_practitioner_line'),
    ('20260901074612','how_you_work_catalogs'),
    ('20260901074638','usp_guardrail_tables'),
    ('20260901074731','project_briefs_how_you_work_columns'),
    ('20260901074802','brief_step_renumber'),
    ('20260901074842','usp_fingerprints'),
    ('20260901074903','usp_distinct_and_banned_phrase_checks'),
    ('20260901074933','project_briefs_data_shape'),
    ('20260901182351','comp_access_grants'),
    ('20260901182419','comp_grant_entitlement'),
    ('20260901190000','codify_rls_auto_enable'),
    ('20260902090000','revoke_internal_function_surface'),
    ('20260903090000','brand_asset_storage'),
    ('20260903140000','wordmark_png_dark'),
    ('20260903160000','asset_catalog_trimmed_dims_null'),
    ('20260903180000','palette_sheet_and_og_image'),
    ('20260903190000','release_generation_credit'),
    ('20260903200000','wordmark_ink_treatments'),
    ('20260903210000','asset_catalog_kind_expansion'),
    ('20260903220000','monogram_and_web_icons'),
    ('20260903230000','color_export_formats'),
    ('20260903240000','social_and_print_assets'),
    ('20260903250000','document_assets'),
    ('20260903260000','launch_checklist_first_week'),
    ('20260903270000','brand_kit_delivered_seen'),
    ('20260903280000','delete_brand_kit'),
    ('20260903290000','home_recent_activity'),
    ('20260905175222','notifications_and_workspaces'),
    ('20260905175503','app_search'),
    ('20260905181048','color_labels'),
    ('20260905182335','asset_downloads'),
    ('20260905185500','asset_sizes_and_formats'),
    ('20260905190204','asset_variant_native_format_normalized'),
    ('20260905191203','asset_version_history'),
    ('20260905194933','brand_images'),
    ('20260906112044','image_regeneration_budget'),
    ('20260906155600','content_items'),
    ('20260906164920','user_uploads'),
    ('20260909094038','check_rewrite_daily_limit'),
    ('20260909100346','raise_image_budgets_and_rewrite_ceiling'),
    ('20260909140552','raise_upload_quotas'),
    ('20260909150116','subscription_trial_end_and_notice'),
    ('20260910082539','retire_monthly_presence_content'),
    ('20260910083735','content_system_schema'),
    ('20260910084320','content_system_rpcs'),
    ('20260910093929','month_counts_exclude_proposed'),
    ('20260910094102','approve_content_month'),
    ('20260910100415','content_items_on_image_text'),
    ('20260910100758','content_item_json_restore_shape'),
    ('20260910102753','content_items_theme'),
    ('20260910144421','content_months_theme_source'),
    ('20260910192157','anonymous_briefs'),
    ('20260910210435','anon_assist_ceiling'),
    ('20260910212308','funnel_events'),
    ('20260910212828','funnel_step_order_correction'),
    ('20260911113747','anon_spend_today'),
    ('20260911133504','orphaned_purchases_on_the_glance'),
    ('20260911170021','probe_does_apply_migration_regrant'),
    ('20260911170458','authority_moves_inside_the_function_body'),
    ('20260911180620','organizations_and_membership'),
    ('20260911180839','projects_organization_id'),
    ('20260911180918','server_only_tables_say_so'),
    ('20260911182533','rls_on_direction_asset_daily_spend'),
    ('20260911190810','the_caller_with_no_identity_is_the_database'),
    ('20260911191432','asset_version_order_is_deterministic'),
    ('20260911193259','the_publishing_journal_needs_a_real_clock'),
    ('20260911195327','grant_plan_allowance_picks_a_purchase_deterministically'),
    ('20260911195907','the_invitation'),
    ('20260912144121','the_charter_and_what_derives_from_it'),
    ('20260912145638','the_charter_rulings'),
    ('20260912153103','a_trial_whose_notice_was_not_delivered_does_not_convert'),
    ('20260912153157','unwarned_trials_proves_it_was_warned'),
    ('20260914072327','the_new_offer_skus'),
    ('20260914073802','a_purchase_that_is_not_a_tier'),
    ('20260914074549','platform_qualification'),
    ('20260914075810','positioning_in_her_patients_words'),
    ('20260914080527','the_directory_profile'),
    ('20260914081457','pages_are_data'),
    ('20260914082152','the_google_listing'),
    ('20260914084054','the_guard_moves_into_the_write'),
    ('20260914091227','the_squarespace_answer'),
    ('20260914091622','a_sku_that_cannot_be_delivered_cannot_be_sold'),
    ('20260914134552','eligibility_is_not_refusal'),
    ('20260915053102','the_catalog_the_anonymous_brief_cannot_read'),
    ('20260915100122','a_title_a_state_does_not_issue'),
    ('20260915101137','an_unverified_state_is_not_sellable'),
    ('20260915122121','a_degree_is_not_a_practice_title'),
    ('20260915125159','the_abbreviation_belongs_to_the_pair'),
    ('20260915135138','the_site_spec_stops_printing_the_handle'),
    ('20260915135207','a_title_can_be_the_antechamber_of_another'),
    ('20260917073026','the_three_corrections_the_seed_undid'),
    ('20260917101844','the_eligibility_messages_say_why'),
    ('20260917101901','a_button_that_breaks_is_not_shown'),
    ('20260920140000','monthly_presence_has_a_chokepoint'),
    ('20260920140100','credit_ledger_append_only'),
    ('20260920150000','content_archetypes'),
    ('20260920150100','topic_bank_and_assignment'),
    ('20260920150200','insight_watch'),
    ('20260920150300','rendered_assets_and_libraries'),
    ('20260920160000','a_diagram_label_is_published_text'),
    ('20260920160100','render_dedup_and_cost_report'),
    ('20260920170000','the_collision_window_is_computed_once'),
    ('20260920180000','a_cte_referenced_once_is_inlined'),
    ('20260921090000','an_item_knows_why_it_was_chosen'),
    ('20260921100000','swap_is_a_draw_not_a_generation'),
    ('20260921110000','a_layout_is_hers_to_change'),
    ('20260921120000','a_post_can_be_asked_for'),
    ('20260921140000','a_refused_attempt_still_cost_money'),
    ('20260923100000','a_paid_batch_survives_a_crash'),
    ('20260923110000','the_bank_never_holds_a_practitioners_lines'),
    ('20260924100000','every_paid_call_is_in_the_book'),
    ('20260924120000','an_eyebrow_is_a_label_not_a_code'),
    ('20260924130000','the_bank_is_counted_before_it_is_drawn'),
    ('20260924140000','an_assignment_that_delivered_nothing_is_not_held'),
    ('20260924150000','a_backup_that_does_not_restore_is_not_a_backup'),
    ('20260924160000','a_licence_number_is_required_in_every_advertisement'),
    ('20260926090000','ethics_immediate_negation'),
    ('20260926120000','a_preflight_can_read_the_quota'),
    ('20260927090000','a_trigger_function_is_never_a_client_call'),
    ('20260927100000','a_paid_inclusion_is_not_a_trial'),
    ('20260927110000','a_stale_subscription_event_does_not_rewrite'),
    ('20260927120000','revoke_from_public_does_not_revoke_from_anon'),
    ('20260927130000','the_licence_number_has_one_authority')),
new_mig(version, name) as (values
    ('20260920140000','monthly_presence_has_a_chokepoint'),
    ('20260920140100','credit_ledger_append_only'),
    ('20260920150000','content_archetypes'),
    ('20260920150100','topic_bank_and_assignment'),
    ('20260920150200','insight_watch'),
    ('20260920150300','rendered_assets_and_libraries'),
    ('20260920160000','a_diagram_label_is_published_text'),
    ('20260920160100','render_dedup_and_cost_report'),
    ('20260920170000','the_collision_window_is_computed_once'),
    ('20260920180000','a_cte_referenced_once_is_inlined'),
    ('20260921090000','an_item_knows_why_it_was_chosen'),
    ('20260921100000','swap_is_a_draw_not_a_generation'),
    ('20260921110000','a_layout_is_hers_to_change'),
    ('20260921120000','a_post_can_be_asked_for'),
    ('20260921140000','a_refused_attempt_still_cost_money'),
    ('20260923100000','a_paid_batch_survives_a_crash'),
    ('20260923110000','the_bank_never_holds_a_practitioners_lines'),
    ('20260924100000','every_paid_call_is_in_the_book'),
    ('20260924120000','an_eyebrow_is_a_label_not_a_code'),
    ('20260924130000','the_bank_is_counted_before_it_is_drawn'),
    ('20260924140000','an_assignment_that_delivered_nothing_is_not_held'),
    ('20260924150000','a_backup_that_does_not_restore_is_not_a_backup'),
    ('20260924160000','a_licence_number_is_required_in_every_advertisement'),
    ('20260926090000','ethics_immediate_negation'),
    ('20260926120000','a_preflight_can_read_the_quota'),
    ('20260927090000','a_trigger_function_is_never_a_client_call'),
    ('20260927100000','a_paid_inclusion_is_not_a_trial'),
    ('20260927110000','a_stale_subscription_event_does_not_rewrite'),
    ('20260927120000','revoke_from_public_does_not_revoke_from_anon'),
    ('20260927130000','the_licence_number_has_one_authority')),
exp_f(sig, owner, acl) as (values
    ('abandon_stale_generation_runs()','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('apply_on_demand_write(uuid,text,text,text,text,text,jsonb,text,uuid,numeric)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('assign_topic_to_kit(uuid,date,text)','postgres','service_role:EXECUTE'),
    ('begin_on_demand_write(uuid,text)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('check_monthly_presence_entitlement(uuid)','postgres','service_role:EXECUTE'),
    ('content_item_valid(jsonb)','postgres','anon:EXECUTE,authenticated:EXECUTE,service_role:EXECUTE'),
    ('content_items_payload_ethics_gate()','postgres','service_role:EXECUTE'),
    ('content_items_valid(jsonb,integer,integer)','postgres','anon:EXECUTE,authenticated:EXECUTE,service_role:EXECUTE'),
    ('content_month_cost(uuid,date)','postgres','service_role:EXECUTE'),
    ('content_topic_bank_payload_valid(text,jsonb)','postgres','anon:EXECUTE,authenticated:EXECUTE,public:EXECUTE,service_role:EXECUTE'),
    ('content_topic_payload_valid(text,jsonb)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('content_topic_text(jsonb)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('content_topics_banned_phrases_gate()','postgres','service_role:EXECUTE'),
    ('content_topics_ethics_gate()','postgres','service_role:EXECUTE'),
    ('content_words(text)','postgres','anon:EXECUTE,authenticated:EXECUTE,service_role:EXECUTE'),
    ('credit_ledger_apply()','postgres','service_role:EXECUTE'),
    ('credit_ledger_is_append_only()','postgres','service_role:EXECUTE'),
    ('credit_meter(date)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('credit_monthly_limit(uuid,text)','postgres','service_role:EXECUTE'),
    ('credit_plan_for(uuid)','postgres','service_role:EXECUTE'),
    ('credit_remaining(uuid,text,date)','postgres','service_role:EXECUTE'),
    ('custom_visual_path(uuid,text)','postgres','service_role:EXECUTE'),
    ('drawable_count_for_kit(uuid)','postgres','service_role:EXECUTE'),
    ('drawable_topics_for_kit(uuid,text)','postgres','service_role:EXECUTE'),
    ('ethics_prohibitive_lead()','postgres','anon:EXECUTE,authenticated:EXECUTE,public:EXECUTE,service_role:EXECUTE'),
    ('insight_cards_validate_segments()','postgres','service_role:EXECUTE'),
    ('licence_number_problem(text)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('licence_number_reprise()','postgres','service_role:EXECUTE'),
    ('monthly_presence_entitled()','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('monthly_presence_past_due_grace()','postgres','anon:EXECUTE,authenticated:EXECUTE,service_role:EXECUTE'),
    ('next_background_for_kit(uuid)','postgres','service_role:EXECUTE'),
    ('next_topic_for_kit(uuid,date,text)','postgres','service_role:EXECUTE'),
    ('project_briefs_licence_number_to_specs()','postgres','service_role:EXECUTE'),
    ('record_custom_visual(uuid,text,uuid,text,text,text,text,numeric,uuid)','postgres','service_role:EXECUTE'),
    ('record_rendered_asset(uuid,text,text,text,text,integer,integer,integer,integer)','postgres','service_role:EXECUTE'),
    ('release_on_demand_write(uuid,numeric)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('release_stale_credit_reservations(interval)','postgres','service_role:EXECUTE'),
    ('release_stale_topic_assignments()','postgres','service_role:EXECUTE'),
    ('render_rationale(text,uuid)','postgres','service_role:EXECUTE'),
    ('rendered_asset_path(uuid,text)','postgres','service_role:EXECUTE'),
    ('reserve_credit(uuid,text,text,text,uuid,numeric,text,text,date)','postgres','service_role:EXECUTE'),
    ('section_types_pages_exist()','postgres','service_role:EXECUTE'),
    ('set_content_item_topic(uuid,uuid,text)','postgres','service_role:EXECUTE'),
    ('settle_credit(uuid,numeric,boolean)','postgres','service_role:EXECUTE'),
    ('site_specs_licence_number_from_brief()','postgres','service_role:EXECUTE'),
    ('subscriptions_refuse_stale_event()','postgres','service_role:EXECUTE'),
    ('suggest_topics_for_kit(uuid,date,integer,uuid[])','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('swap_content_item(uuid)','postgres','authenticated:EXECUTE,service_role:EXECUTE'),
    ('topic_assignment_grace()','postgres','anon:EXECUTE,authenticated:EXECUTE,public:EXECUTE,service_role:EXECUTE'),
    ('topic_assignment_holds(uuid,uuid,timestamp with time zone)','postgres','anon:EXECUTE,authenticated:EXECUTE,public:EXECUTE,service_role:EXECUTE'),
    ('topic_collision_window()','postgres','anon:EXECUTE,authenticated:EXECUTE,service_role:EXECUTE')),
exp_r(rel, owner, acl, rls) as (values
    ('background_assignments','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('background_library','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('content_archetypes','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('content_generation_results','postgres','service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('content_generation_runs','postgres','service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('content_intents','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('content_segments','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('content_topics','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('credit_balances','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('credit_ledger','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('credit_month_audit','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','false'),
    ('credit_quotas','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('custom_visual_generations','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('illustration_library','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('insight_cards','postgres','service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('insight_runs','postgres','service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('insight_sources','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('on_demand_writes','postgres','service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('rendered_assets','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true'),
    ('topic_assignments','postgres','anon:DELETE,anon:INSERT,anon:SELECT,anon:UPDATE,authenticated:DELETE,authenticated:INSERT,authenticated:SELECT,authenticated:UPDATE,service_role:DELETE,service_role:INSERT,service_role:SELECT,service_role:UPDATE','true')),
exp_c(col, typ) as (values
    ('background_assignments.asset_id','uuid'),
    ('background_assignments.assigned_at','timestamp with time zone'),
    ('background_assignments.brand_kit_id','uuid'),
    ('background_library.active','boolean'),
    ('background_library.created_at','timestamp with time zone'),
    ('background_library.id','uuid'),
    ('background_library.slug','text'),
    ('background_library.storage_path','text'),
    ('background_library.treatment','text'),
    ('content_archetypes.active','boolean'),
    ('content_archetypes.id','text'),
    ('content_archetypes.illustration_zone','text'),
    ('content_archetypes.is_multi_card','boolean'),
    ('content_archetypes.items_max','smallint'),
    ('content_archetypes.items_min','smallint'),
    ('content_archetypes.label','text'),
    ('content_archetypes.sort_order','smallint'),
    ('content_generation_results.created_at','timestamp with time zone'),
    ('content_generation_results.id','uuid'),
    ('content_generation_results.result','jsonb'),
    ('content_generation_results.run_id','uuid'),
    ('content_generation_results.settled','boolean'),
    ('content_generation_results.topic_id','uuid'),
    ('content_generation_results.usage','jsonb'),
    ('content_generation_runs.batch_id','text'),
    ('content_generation_runs.brand_kit_id','uuid'),
    ('content_generation_runs.closed_at','timestamp with time zone'),
    ('content_generation_runs.cost_usd','numeric'),
    ('content_generation_runs.created_at','timestamp with time zone'),
    ('content_generation_runs.id','uuid'),
    ('content_generation_runs.month','date'),
    ('content_generation_runs.state','text'),
    ('content_generation_runs.updated_at','timestamp with time zone'),
    ('content_intents.id','text'),
    ('content_intents.label','text'),
    ('content_intents.sort_order','smallint'),
    ('content_items.compose_archetype','text'),
    ('content_items.payload','jsonb'),
    ('content_items.rationale','text'),
    ('content_items.topic_id','uuid'),
    ('content_segments.created_at','timestamp with time zone'),
    ('content_segments.id','uuid'),
    ('content_segments.modality_id','text'),
    ('content_segments.persona_id','text'),
    ('content_segments.state_code','character'),
    ('content_topics.archetype_key','text'),
    ('content_topics.caption_seed','text'),
    ('content_topics.created_at','timestamp with time zone'),
    ('content_topics.ethics_reviewed_at','timestamp with time zone'),
    ('content_topics.expires_at','timestamp with time zone'),
    ('content_topics.generation_batch_id','uuid'),
    ('content_topics.hook','text'),
    ('content_topics.id','uuid'),
    ('content_topics.insight_card_id','uuid'),
    ('content_topics.intent','text'),
    ('content_topics.payload','jsonb'),
    ('content_topics.rationale_template','text'),
    ('content_topics.segment_id','uuid'),
    ('content_topics.timely','boolean'),
    ('content_topics.title','text'),
    ('credit_balances.actual_cost_usd','numeric'),
    ('credit_balances.consumed','integer'),
    ('credit_balances.estimated_cost_usd','numeric'),
    ('credit_balances.kind','text'),
    ('credit_balances.month','date'),
    ('credit_balances.releases','integer'),
    ('credit_balances.reservations','integer'),
    ('credit_balances.settlements','integer'),
    ('credit_balances.updated_at','timestamp with time zone'),
    ('credit_balances.user_id','uuid'),
    ('credit_ledger.actual_cost_usd','numeric'),
    ('credit_ledger.created_at','timestamp with time zone'),
    ('credit_ledger.delta','integer'),
    ('credit_ledger.entry_type','text'),
    ('credit_ledger.estimated_cost_usd','numeric'),
    ('credit_ledger.id','uuid'),
    ('credit_ledger.kind','text'),
    ('credit_ledger.model','text'),
    ('credit_ledger.month','date'),
    ('credit_ledger.provider','text'),
    ('credit_ledger.reason','text'),
    ('credit_ledger.ref_id','uuid'),
    ('credit_ledger.ref_type','text'),
    ('credit_ledger.reservation_id','uuid'),
    ('credit_ledger.user_id','uuid'),
    ('credit_month_audit.cost_usd','numeric'),
    ('credit_month_audit.kind','text'),
    ('credit_month_audit.month','date'),
    ('credit_month_audit.releases','bigint'),
    ('credit_month_audit.reservations','bigint'),
    ('credit_month_audit.settlements','bigint'),
    ('credit_month_audit.user_id','uuid'),
    ('credit_quotas.kind','text'),
    ('credit_quotas.monthly_limit','integer'),
    ('credit_quotas.plan','text'),
    ('custom_visual_generations.brand_kit_id','uuid'),
    ('custom_visual_generations.content_item_id','uuid'),
    ('custom_visual_generations.cost_usd','numeric'),
    ('custom_visual_generations.created_at','timestamp with time zone'),
    ('custom_visual_generations.id','uuid'),
    ('custom_visual_generations.model','text'),
    ('custom_visual_generations.prompt_hash','text'),
    ('custom_visual_generations.quality','text'),
    ('custom_visual_generations.reservation_id','uuid'),
    ('custom_visual_generations.size','text'),
    ('custom_visual_generations.storage_path','text'),
    ('illustration_library.active','boolean'),
    ('illustration_library.archetype_key','text'),
    ('illustration_library.created_at','timestamp with time zone'),
    ('illustration_library.id','uuid'),
    ('illustration_library.slug','text'),
    ('illustration_library.svg','text'),
    ('illustration_library.version','smallint'),
    ('insight_cards.created_at','timestamp with time zone'),
    ('insight_cards.expires_at','timestamp with time zone'),
    ('insight_cards.id','uuid'),
    ('insight_cards.published_at','timestamp with time zone'),
    ('insight_cards.run_id','uuid'),
    ('insight_cards.segments','ARRAY'),
    ('insight_cards.source_id','text'),
    ('insight_cards.summary','text'),
    ('insight_runs.finished_at','timestamp with time zone'),
    ('insight_runs.id','uuid'),
    ('insight_runs.searches_used','integer'),
    ('insight_runs.started_at','timestamp with time zone'),
    ('insight_runs.state','text'),
    ('insight_runs.week','date'),
    ('insight_sources.active','boolean'),
    ('insight_sources.id','text'),
    ('insight_sources.kind','text'),
    ('insight_sources.label','text'),
    ('insight_sources.sort_order','smallint'),
    ('insight_sources.url','text'),
    ('on_demand_writes.content_item_id','uuid'),
    ('on_demand_writes.created_at','timestamp with time zone'),
    ('on_demand_writes.idempotency_key','text'),
    ('on_demand_writes.id','uuid'),
    ('on_demand_writes.reservation_id','uuid'),
    ('on_demand_writes.settled_at','timestamp with time zone'),
    ('on_demand_writes.state','text'),
    ('project_briefs.license_number','text'),
    ('project_briefs.license_state_code','character'),
    ('rendered_assets.archetype_key','text'),
    ('rendered_assets.brand_kit_id','uuid'),
    ('rendered_assets.bytes','integer'),
    ('rendered_assets.content_hash','text'),
    ('rendered_assets.created_at','timestamp with time zone'),
    ('rendered_assets.height','integer'),
    ('rendered_assets.id','uuid'),
    ('rendered_assets.palette_key','text'),
    ('rendered_assets.render_ms','integer'),
    ('rendered_assets.storage_path','text'),
    ('rendered_assets.width','integer'),
    ('subscriptions.stripe_event_at','timestamp with time zone'),
    ('topic_assignments.assigned_at','timestamp with time zone'),
    ('topic_assignments.brand_kit_id','uuid'),
    ('topic_assignments.month','date'),
    ('topic_assignments.topic_id','uuid')),
exp_t(trg) as (values
    ('content_items.content_items_payload_ethics_gate'),
    ('content_topics.content_topics_banned_phrases_gate'),
    ('content_topics.content_topics_ethics_gate'),
    ('credit_ledger.credit_ledger_apply'),
    ('credit_ledger.credit_ledger_no_delete'),
    ('credit_ledger.credit_ledger_no_update'),
    ('insight_cards.insight_cards_validate_segments'),
    ('project_briefs.project_briefs_licence_number_to_specs'),
    ('section_types.section_types_pages_exist_trigger'),
    ('site_specs.site_specs_licence_number_from_brief'),
    ('subscriptions.subscriptions_refuse_stale_event')),
exp_p(pol) as (values
    ('background_assignments.background_assignments_delete_denied'),
    ('background_assignments.background_assignments_insert_denied'),
    ('background_assignments.background_assignments_select_own'),
    ('background_assignments.background_assignments_update_denied'),
    ('background_library.background_library_delete_denied'),
    ('background_library.background_library_insert_denied'),
    ('background_library.background_library_select_all'),
    ('background_library.background_library_update_denied'),
    ('content_archetypes.content_archetypes_delete_denied'),
    ('content_archetypes.content_archetypes_insert_denied'),
    ('content_archetypes.content_archetypes_select_all'),
    ('content_archetypes.content_archetypes_update_denied'),
    ('content_generation_results.content_generation_results_no_browser'),
    ('content_generation_runs.content_generation_runs_no_browser'),
    ('content_intents.content_intents_delete_denied'),
    ('content_intents.content_intents_insert_denied'),
    ('content_intents.content_intents_select_all'),
    ('content_intents.content_intents_update_denied'),
    ('content_segments.content_segments_delete_denied'),
    ('content_segments.content_segments_insert_denied'),
    ('content_segments.content_segments_select_all'),
    ('content_segments.content_segments_update_denied'),
    ('content_topics.content_topics_delete_denied'),
    ('content_topics.content_topics_insert_denied'),
    ('content_topics.content_topics_select_assigned'),
    ('content_topics.content_topics_update_denied'),
    ('credit_balances.credit_balances_delete_denied'),
    ('credit_balances.credit_balances_insert_denied'),
    ('credit_balances.credit_balances_select_own'),
    ('credit_balances.credit_balances_update_denied'),
    ('credit_ledger.credit_ledger_delete_denied'),
    ('credit_ledger.credit_ledger_insert_denied'),
    ('credit_ledger.credit_ledger_select_own'),
    ('credit_ledger.credit_ledger_update_denied'),
    ('credit_quotas.credit_quotas_delete_denied'),
    ('credit_quotas.credit_quotas_insert_denied'),
    ('credit_quotas.credit_quotas_select_all'),
    ('credit_quotas.credit_quotas_update_denied'),
    ('custom_visual_generations.custom_visual_delete_denied'),
    ('custom_visual_generations.custom_visual_insert_denied'),
    ('custom_visual_generations.custom_visual_select_own'),
    ('custom_visual_generations.custom_visual_update_denied'),
    ('illustration_library.illustration_library_delete_denied'),
    ('illustration_library.illustration_library_insert_denied'),
    ('illustration_library.illustration_library_select_all'),
    ('illustration_library.illustration_library_update_denied'),
    ('insight_cards.insight_cards_denied'),
    ('insight_runs.insight_runs_denied'),
    ('insight_sources.insight_sources_delete_denied'),
    ('insight_sources.insight_sources_insert_denied'),
    ('insight_sources.insight_sources_select_all'),
    ('insight_sources.insight_sources_update_denied'),
    ('on_demand_writes.on_demand_writes_no_browser'),
    ('rendered_assets.rendered_assets_delete_denied'),
    ('rendered_assets.rendered_assets_insert_denied'),
    ('rendered_assets.rendered_assets_select_own'),
    ('rendered_assets.rendered_assets_update_denied'),
    ('topic_assignments.topic_assignments_delete_denied'),
    ('topic_assignments.topic_assignments_insert_denied'),
    ('topic_assignments.topic_assignments_select_own'),
    ('topic_assignments.topic_assignments_update_denied')),
act_f as (
  select p.oid::regprocedure::text as sig, pg_get_userbyid(p.proowner) as owner, coalesce((select string_agg(case when e.grantee = 0 then 'public' else pg_get_userbyid(e.grantee) end || ':' || e.privilege_type, ',' order by case when e.grantee = 0 then 'public' else pg_get_userbyid(e.grantee) end, e.privilege_type) from aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) e where e.grantee = 0 or pg_get_userbyid(e.grantee) in ('anon','authenticated','service_role')), '-') as acl
    from pg_proc p where p.pronamespace = 'public'::regnamespace),
act_r as (
  select c.oid::regclass::text as rel, pg_get_userbyid(c.relowner) as owner, coalesce((select string_agg(case when e.grantee = 0 then 'public' else pg_get_userbyid(e.grantee) end || ':' || e.privilege_type, ',' order by case when e.grantee = 0 then 'public' else pg_get_userbyid(e.grantee) end, e.privilege_type) from aclexplode(coalesce(c.relacl, acldefault('r', c.relowner))) e where e.grantee = 0 or pg_get_userbyid(e.grantee) in ('anon','authenticated','service_role')), '-') as acl,
         c.relrowsecurity::text as rls
    from pg_class c where c.relnamespace = 'public'::regnamespace and c.relkind in ('r','v','m','S','p')),
checks(ordre, controle, bad, total, detail) as (
  select 1, 'registre : les 163 migrations du dépôt enregistrées',
         (select count(*) from mig m where not exists (select 1 from supabase_migrations.schema_migrations s where s.version = m.version)),
         163,
         (select 'absentes : ' || string_agg(m.version, ' ') from mig m
           where not exists (select 1 from supabase_migrations.schema_migrations s where s.version = m.version))
  union all
  select 2, 'registre : total = 163, rien de plus',
         (select abs(count(*) - 163) from supabase_migrations.schema_migrations), 163,
         (select 'enregistrées : ' || count(*) || ' ; hors dépôt : ' || coalesce(string_agg(s.version, ' ') filter (where m.version is null), 'aucune')
            from supabase_migrations.schema_migrations s left join mig m on m.version = s.version)
  union all
  select 3, 'registre : les 30 nouvelles sous le nom de leur fichier',
         (select count(*) from new_mig n where not exists
            (select 1 from supabase_migrations.schema_migrations s where s.version = n.version and s.name = n.name)),
         30,
         (select 'absentes ou mal nommées : ' || string_agg(n.version, ' ') from new_mig n where not exists
            (select 1 from supabase_migrations.schema_migrations s where s.version = n.version and s.name = n.name))
  union all
  select 4, 'dérive : les 51 fonctions créées, propriétaire et droits exacts',
         (select count(*) from exp_f e left join act_f a using (sig)
           where a.sig is null or a.owner <> e.owner or a.acl <> e.acl),
         51,
         (select string_agg(e.sig || case when a.sig is null then ' ABSENTE' when a.owner <> e.owner then ' propriétaire ' || a.owner
                                          else ' droits ' || a.acl || ' attendus ' || e.acl end, ' ; ')
            from exp_f e left join act_f a using (sig)
           where a.sig is null or a.owner <> e.owner or a.acl <> e.acl)
  union all
  select 5, 'dérive : les 20 tables et vues créées, propriétaire, droits et RLS exacts',
         (select count(*) from exp_r e left join act_r a using (rel)
           where a.rel is null or a.owner <> e.owner or a.acl <> e.acl or a.rls <> e.rls),
         20,
         (select string_agg(e.rel || case when a.rel is null then ' ABSENTE' when a.rls <> e.rls then ' RLS ' || a.rls
                                          when a.owner <> e.owner then ' propriétaire ' || a.owner else ' droits ' || a.acl end, ' ; ')
            from exp_r e left join act_r a using (rel)
           where a.rel is null or a.owner <> e.owner or a.acl <> e.acl or a.rls <> e.rls)
  union all
  select 6, 'dérive : les 158 colonnes ajoutées, au bon type',
         (select count(*) from exp_c e where not exists (select 1 from information_schema.columns c
            where c.table_schema = 'public' and c.table_name || '.' || c.column_name = e.col and c.data_type = e.typ)),
         158,
         (select 'absentes ou mal typées : ' || string_agg(e.col, ' ') from exp_c e where not exists (select 1 from information_schema.columns c
            where c.table_schema = 'public' and c.table_name || '.' || c.column_name = e.col and c.data_type = e.typ))
  union all
  select 7, 'dérive : les 11 triggers ajoutés',
         (select count(*) from exp_t e where not exists (select 1 from pg_trigger t
            where not t.tgisinternal and t.tgrelid::regclass::text || '.' || t.tgname = e.trg)),
         11,
         (select 'absents : ' || string_agg(e.trg, ' ') from exp_t e where not exists (select 1 from pg_trigger t
            where not t.tgisinternal and t.tgrelid::regclass::text || '.' || t.tgname = e.trg))
  union all
  select 8, 'dérive : les 61 policies ajoutées',
         (select count(*) from exp_p e where not exists (select 1 from pg_policies p
            where p.schemaname = 'public' and p.tablename || '.' || p.policyname = e.pol)),
         61,
         (select 'absentes : ' || string_agg(e.pol, ' ') from exp_p e where not exists (select 1 from pg_policies p
            where p.schemaname = 'public' and p.tablename || '.' || p.policyname = e.pol))
  union all
  select 9, 'F63 : les 4 fonctions privilégiées existent et sont FERMÉES à anon',
         (select 4 - count(*) filter (where not has_function_privilege('anon', p.oid, 'execute')) from pg_proc p
           where p.pronamespace = 'public'::regnamespace
             and p.proname in ('credit_remaining','drawable_count_for_kit','drawable_topics_for_kit','release_stale_topic_assignments')),
         4,
         (select 'trouvées : ' || count(*) || ' ; ouvertes à anon : ' ||
                 coalesce(string_agg(p.proname, ', ') filter (where has_function_privilege('anon', p.oid, 'execute')), 'aucune')
            from pg_proc p where p.pronamespace = 'public'::regnamespace
             and p.proname in ('credit_remaining','drawable_count_for_kit','drawable_topics_for_kit','release_stale_topic_assignments'))
  union all
  select 10, 'F61 : subscriptions.stripe_event_at et le trigger qui refuse un event en retard',
         (select 2 - (select count(*) from information_schema.columns where table_schema='public' and table_name='subscriptions' and column_name='stripe_event_at')
                   - (select count(*) from pg_trigger where not tgisinternal and tgname = 'subscriptions_refuse_stale_event')),
         2, null
  union all
  select 11, 'F64 : les deux triggers qui tiennent le numéro de licence sur le brief',
         (select 2 - count(*) from pg_trigger where not tgisinternal
           and tgname in ('site_specs_licence_number_from_brief','project_briefs_licence_number_to_specs')),
         2, null
)
select controle as "contrôle",
       case when bad = 0 then 'OK' else 'PAS OK' end as statut,
       case when bad = 0 then total || '/' || total else coalesce(detail, (total - bad) || '/' || total) end as "détail"
  from checks order by ordre;
